tgs: tgs.parsers.svg.handler.SvgHandler Class Reference
tgs.parsers.svg.handler.SvgHandler Class Reference
Public Member Functions
def init_etree (self)
def qualified (self, ns, name)
def simplified (self, name)
def unqualified (self, name)
def __init__ (self)
Static Public Attributes
dictionary ns_map
Detailed Description
Definition at line 5 of file handler.py.
Constructor & Destructor Documentation
__init__()
def tgs.parsers.svg.handler.SvgHandler.__init__ (self)
Definition at line 31 of file handler.py.
References tgs.parsers.svg.handler.SvgHandler.init_etree().
Member Function Documentation
init_etree()
def tgs.parsers.svg.handler.SvgHandler.init_etree (self)
Definition at line 16 of file handler.py.
References tgs.parsers.svg.handler.SvgHandler.ns_map.
Referenced by tgs.parsers.svg.handler.SvgHandler.__init__(), and tgs.parsers.svg.importer.SvgParser.__init__().
qualified()
def tgs.parsers.svg.handler.SvgHandler.qualified (self, ns, name)
Definition at line 20 of file handler.py.
References tgs.parsers.svg.handler.SvgHandler.ns_map.
Referenced by tgs.parsers.svg.importer.SvgParser.add_shapes(), tgs.parsers.svg.builder.SvgBuilder.group_from_lottie(), tgs.parsers.svg.importer.SvgParser.parse_etree(), tgs.parsers.svg.importer.SvgParser.parse_transform(), and tgs.parsers.svg.builder.SvgBuilder.set_id().
simplified()
def tgs.parsers.svg.handler.SvgHandler.simplified (self, name)
Definition at line 23 of file handler.py.
References tgs.parsers.svg.handler.SvgHandler.ns_map.
unqualified()
def tgs.parsers.svg.handler.SvgHandler.unqualified (self, name)
Definition at line 28 of file handler.py.
Referenced by tgs.parsers.svg.importer.SvgParser.parse_children().
Member Data Documentation
ns_map
dictionary tgs.parsers.svg.handler.SvgHandler.ns_map static
Initial value:
=  {
        "dc": "http://purl.org/dc/elements/1.1/",
        "cc": "http://creativecommons.org/ns#",
        "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
        "svg": "http://www.w3.org/2000/svg",
        "sodipodi": "http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd",
        "inkscape": "http://www.inkscape.org/namespaces/inkscape",
        "xlink": "http://www.w3.org/1999/xlink",
    }
Definition at line 6 of file handler.py.
Referenced by tgs.parsers.svg.handler.SvgHandler.init_etree(), tgs.parsers.svg.handler.SvgHandler.qualified(), and tgs.parsers.svg.handler.SvgHandler.simplified().
The documentation for this class was generated from the following file:
tgs/parsers/svg/handler.py