tgs: tgs.utils.ik.Octopus Class Reference
tgs.utils.ik.Octopus Class Reference
Public Member Functions
def __init__ (self, master)
def base (self)
def add_chain (self, name)
def reach (self, target_map)
Public Attributes
chains
master
Detailed Description
Definition at line 73 of file ik.py.
Constructor & Destructor Documentation
__init__()
def tgs.utils.ik.Octopus.__init__ (self, master)
Definition at line 74 of file ik.py.
Member Function Documentation
add_chain()
def tgs.utils.ik.Octopus.add_chain (self, name)
Definition at line 82 of file ik.py.
References tgs.utils.ik.Octopus.base(), and tgs.utils.ik.Octopus.chains.
base()
def tgs.utils.ik.Octopus.base (self)
Definition at line 79 of file ik.py.
References tgs.utils.ik.Octopus.master.
Referenced by tgs.utils.ik.Octopus.add_chain(), and tgs.utils.ik.Octopus.reach().
reach()
def tgs.utils.ik.Octopus.reach (self, target_map)
Definition at line 87 of file ik.py.
References tgs.utils.ik.Octopus.base(), tgs.utils.ik.Octopus.chains, and tgs.utils.ik.Octopus.master.
Member Data Documentation
chains
tgs.utils.ik.Octopus.chains
Definition at line 75 of file ik.py.
Referenced by tgs.utils.ik.Octopus.add_chain(), and tgs.utils.ik.Octopus.reach().
master
tgs.utils.ik.Octopus.master
Definition at line 76 of file ik.py.
Referenced by tgs.utils.ik.Octopus.base(), and tgs.utils.ik.Octopus.reach().
The documentation for this class was generated from the following file:
tgs/utils/ik.py