tgs: tgs.parsers.raster.RasterImage Class Reference
tgs.parsers.raster.RasterImage Class Reference
Public Member Functions
def __init__ (self, data)
def from_pil (cls, image)
def open (cls, filename)
def k_means (self, n_colors)
def get_alpha (self, row, column)
def quantize (self, codebook, quantization_mode=QuanzationMode.Nearest)
def mono (self)
Public Attributes
data
Detailed Description
Definition at line 16 of file raster.py.
Constructor & Destructor Documentation
__init__()
def tgs.parsers.raster.RasterImage.__init__ (self, data)
Definition at line 17 of file raster.py.
Member Function Documentation
from_pil()
def tgs.parsers.raster.RasterImage.from_pil (cls, image)
Definition at line 21 of file raster.py.
Referenced by tgs.parsers.raster.RasterImage.open().
get_alpha()
def tgs.parsers.raster.RasterImage.get_alpha (self, row, column)
Definition at line 41 of file raster.py.
References tgs.parsers.raster.RasterImage.data.
Referenced by tgs.parsers.raster.RasterImage.k_means(), and tgs.parsers.raster.RasterImage.quantize().
k_means()
def tgs.parsers.raster.RasterImage.k_means (self, n_colors)
Returns a list of centroids
Definition at line 28 of file raster.py.
References tgs.parsers.raster.RasterImage.data, and tgs.parsers.raster.RasterImage.get_alpha().
mono()
def tgs.parsers.raster.RasterImage.mono (self)
Returns a bit mask of opaque pixels
Definition at line 82 of file raster.py.
References tgs.parsers.raster.RasterImage.data.
Referenced by tgs.parsers.raster.RasterImage.quantize().
open()
def tgs.parsers.raster.RasterImage.open (cls, filename)
Definition at line 25 of file raster.py.
References tgs.parsers.raster.RasterImage.from_pil().
quantize()
def tgs.parsers.raster.RasterImage.quantize (self, codebook, quantization_mode = QuanzationMode.Nearest)
Returns a list of tuple [color, data] where for each color in codebook
data is a bit mask for the image
You can get codebook from k_means
Definition at line 46 of file raster.py.
References tgs.parsers.raster.RasterImage.data, tgs.parsers.raster.RasterImage.get_alpha(), and tgs.parsers.raster.RasterImage.mono().
Member Data Documentation
data
tgs.parsers.raster.RasterImage.data
Definition at line 18 of file raster.py.
Referenced by tgs.parsers.raster.RasterImage.get_alpha(), tgs.parsers.raster.RasterImage.k_means(), tgs.parsers.raster.RasterImage.mono(), and tgs.parsers.raster.RasterImage.quantize().
The documentation for this class was generated from the following file:
tgs/parsers/raster.py