tgs: tgs.utils.animation.DepthRotation Class Reference
tgs.utils.animation.DepthRotation Class Reference
Public Member Functions
def __init__ (self, center)
def rotate3d_y (self, point, angle)
def rotate3d_x (self, point, angle)
def rotate3d_z (self, point, angle)
def rotate3d (self, point, angle, axis)
Public Attributes
center
Static Public Attributes
axis_x = DepthRotationAxis(NVector(0, 0, 1), NVector(0, 1, 0), NVector(1, 0, 0))
axis_y = DepthRotationAxis(NVector(1, 0, 0), NVector(0, 0, 1), NVector(0, 1, 0))
axis_z = DepthRotationAxis(NVector(1, 0, 0), NVector(0, 1, 0), NVector(0, 0, 1))
Detailed Description
Definition at line 330 of file animation.py.
Constructor & Destructor Documentation
__init__()
def tgs.utils.animation.DepthRotation.__init__ (self, center)
Definition at line 335 of file animation.py.
Member Function Documentation
rotate3d()
def tgs.utils.animation.DepthRotation.rotate3d (self, point, angle, axis)
Definition at line 371 of file animation.py.
References tgs.utils.animation.DepthRotation.center.
Referenced by tgs.utils.animation.DepthRotation.rotate3d_x(), tgs.utils.animation.DepthRotation.rotate3d_y(), and tgs.utils.animation.DepthRotation.rotate3d_z().
rotate3d_x()
def tgs.utils.animation.DepthRotation.rotate3d_x (self, point, angle)
Definition at line 353 of file animation.py.
References tgs.utils.animation.DepthRotation.axis_x, and tgs.utils.animation.DepthRotation.rotate3d().
rotate3d_y()
def tgs.utils.animation.DepthRotation.rotate3d_y (self, point, angle)
Definition at line 338 of file animation.py.
References tgs.utils.animation.DepthRotation.axis_y, and tgs.utils.animation.DepthRotation.rotate3d().
rotate3d_z()
def tgs.utils.animation.DepthRotation.rotate3d_z (self, point, angle)
Definition at line 368 of file animation.py.
References tgs.utils.animation.DepthRotation.axis_z, and tgs.utils.animation.DepthRotation.rotate3d().
Member Data Documentation
axis_x
tgs.utils.animation.DepthRotation.axis_x = DepthRotationAxis(NVector(0, 0, 1), NVector(0, 1, 0), NVector(1, 0, 0)) static
Definition at line 331 of file animation.py.
Referenced by tgs.utils.animation.DepthRotation.rotate3d_x().
axis_y
tgs.utils.animation.DepthRotation.axis_y = DepthRotationAxis(NVector(1, 0, 0), NVector(0, 0, 1), NVector(0, 1, 0)) static
Definition at line 332 of file animation.py.
Referenced by tgs.utils.animation.DepthRotation.rotate3d_y().
axis_z
tgs.utils.animation.DepthRotation.axis_z = DepthRotationAxis(NVector(1, 0, 0), NVector(0, 1, 0), NVector(0, 0, 1)) static
Definition at line 333 of file animation.py.
Referenced by tgs.utils.animation.DepthRotation.rotate3d_z().
center
tgs.utils.animation.DepthRotation.center
Definition at line 336 of file animation.py.
Referenced by tgs.utils.ellipse.Ellipse.point(), and tgs.utils.animation.DepthRotation.rotate3d().
The documentation for this class was generated from the following file:
tgs/utils/animation.py