tgs: tgs.utils.restructure Namespace Reference
tgs.utils.restructure Namespace Reference
Classes
class AbstractBuilder
class RestructuredLayer
class RestructuredPathMerger
class RestructuredShapeGroup
Functions
def restructure_animation (animation, merge_paths)
def restructure_shapegroup (shape, shape_group, merge_paths)
Function Documentation
restructure_animation()
def tgs.utils.restructure.restructure_animation (animation, merge_paths)
Definition at line 54 of file restructure.py.
References tgs.utils.restructure.restructure_shapegroup().
Referenced by tgs.utils.restructure.AbstractBuilder.process().
restructure_shapegroup()
def tgs.utils.restructure.restructure_shapegroup (shape, shape_group, merge_paths)
Definition at line 78 of file restructure.py.
Referenced by tgs.utils.restructure.restructure_animation().