tgs: tgs.exporters Namespace Reference
tgs.exporters Namespace Reference
Functions
def export_lottie (animation, fp, kw)
def export_tgs (animation, file)
def lottie_display_html_pre (width=512, height=512)
def lottie_display_html_post ()
def export_embedded_html (animation, fp)
def export_linked_html (fp, path)
def prettyprint (tgs_object, out=sys.stdout, indent=" ", _i="")
def prettyprint_summary (tgs_object, out=sys.stdout, indent=" ", _i="")
def multiexport (animation, basename, lottie_json=True, lottie_html=True, tgs=True, embedded_html=True)
def export_svg (animation, fp, time=0, pretty=True)
def export_sif (animation, fp, pretty=True)
Function Documentation
export_embedded_html()
def tgs.exporters.export_embedded_html (animation, fp)
Definition at line 66 of file exporters.py.
References tgs.exporters.export_lottie(), tgs.exporters.lottie_display_html_post(), and tgs.exporters.lottie_display_html_pre().
Referenced by tgs.exporters.multiexport().
export_linked_html()
def tgs.exporters.export_linked_html (fp, path)
Definition at line 75 of file exporters.py.
References tgs.exporters.lottie_display_html_post(), and tgs.exporters.lottie_display_html_pre().
Referenced by tgs.exporters.multiexport().
export_lottie()
def tgs.exporters.export_lottie (animation, fp, kw)
Definition at line 14 of file exporters.py.
Referenced by tgs.exporters.export_embedded_html(), tgs.exporters.export_tgs(), and tgs.exporters.multiexport().
export_sif()
def tgs.exporters.export_sif (animation, fp, pretty = True)
Definition at line 179 of file exporters.py.
References tgs.parsers.sif.builder.to_sif().
export_svg()
def tgs.exporters.export_svg (animation, fp, time = 0, pretty = True)
Definition at line 174 of file exporters.py.
References tgs.parsers.svg.builder.to_svg().
export_tgs()
def tgs.exporters.export_tgs (animation, file)
Definition at line 18 of file exporters.py.
References tgs.exporters.export_lottie().
Referenced by tgs.exporters.multiexport().
lottie_display_html_post()
def tgs.exporters.lottie_display_html_post ()
Definition at line 57 of file exporters.py.
Referenced by tgs.exporters.export_embedded_html(), and tgs.exporters.export_linked_html().
lottie_display_html_pre()
def tgs.exporters.lottie_display_html_pre (width = 512, height = 512)
Definition at line 23 of file exporters.py.
Referenced by tgs.exporters.export_embedded_html(), and tgs.exporters.export_linked_html().
multiexport()
def tgs.exporters.multiexport (animation, basename, lottie_json = True, lottie_html = True, tgs = True, embedded_html = True)
Definition at line 147 of file exporters.py.
References tgs.exporters.export_embedded_html(), tgs.exporters.export_linked_html(), tgs.exporters.export_lottie(), and tgs.exporters.export_tgs().
prettyprint()
def tgs.exporters.prettyprint (tgs_object, out = sys.stdout, indent = " ", _i = "")
Definition at line 89 of file exporters.py.
Referenced by tgs.utils.linediff.difflines().
prettyprint_summary()
def tgs.exporters.prettyprint_summary (tgs_object, out = sys.stdout, indent = " ", _i = "")
Definition at line 123 of file exporters.py.