tgs: tgs.utils.nvector Namespace Reference
tgs.utils.nvector Namespace Reference
Classes
class NVector
Functions
def vop (op, a, b)
def Point (x, y)
def Size (x, y)
def Point3D (x, y, z)
def Color (r, g, b)
def PolarVector (length, theta)
Function Documentation
Color()
def tgs.utils.nvector.Color (r, g, b)
Definition at line 130 of file nvector.py.
Point()
def tgs.utils.nvector.Point (x, y)
Definition at line 118 of file nvector.py.
Point3D()
def tgs.utils.nvector.Point3D (x, y, z)
Definition at line 126 of file nvector.py.
PolarVector()
def tgs.utils.nvector.PolarVector (length, theta)
Definition at line 137 of file nvector.py.
Size()
def tgs.utils.nvector.Size (x, y)
Definition at line 122 of file nvector.py.
vop()
def tgs.utils.nvector.vop (op, a, b)
Definition at line 5 of file nvector.py.
Referenced by tgs.utils.nvector.NVector.__add__(), tgs.utils.nvector.NVector.__iadd__(), tgs.utils.nvector.NVector.__isub__(), tgs.utils.nvector.NVector.__sub__(), and tgs.utils.nvector.NVector.element_scaled().