tgs: tgs.parsers.raster Namespace Reference
tgs.parsers.raster Namespace Reference
Classes
class QuanzationMode
class RasterImage
class Vectorizer
Functions
def raster_to_animation (filename, n_colors=1, palette=[], mode=QuanzationMode.Nearest)
def color2numpy (vcolor)
def raster_frames_to_animation (files, n_colors=1, frame_delay=1, start_time=0, looping=True, framerate=60, palette=[], mode=QuanzationMode.Nearest)
Function Documentation
color2numpy()
def tgs.parsers.raster.color2numpy (vcolor)
Definition at line 205 of file raster.py.
References tgs.parsers.raster.raster_frames_to_animation().
Referenced by tgs.parsers.raster.raster_frames_to_animation().
raster_frames_to_animation()
def tgs.parsers.raster.raster_frames_to_animation (files, n_colors = 1, frame_delay = 1, start_time = 0, looping = True, framerate = 60, palette = [], mode = QuanzationMode.Nearest)
Definition at line 213 of file raster.py.
References tgs.parsers.raster.color2numpy().
Referenced by tgs.parsers.raster.color2numpy().
raster_to_animation()
def tgs.parsers.raster.raster_to_animation (filename, n_colors = 1, palette = [], mode = QuanzationMode.Nearest)
Definition at line 193 of file raster.py.