tgs: tgs.parsers.svg.importer Namespace Reference
tgs.parsers.svg.importer Namespace Reference
Classes
class PathDParser
class SvgGradient
class SvgGradientCoord
class SvgLinearGradient
class SvgParser
class SvgRadialGradient
Functions
def hsl_to_rgb (h, s, l)
def hue_to_rgb (m1, m2, h)
def parse_color (color, current_color=NVector(0, 0, 0, 1))
def parse_svg_etree (etree, args, kwargs)
def parse_svg_file (file, args, kwargs)
Variables
dictionary nocolor = {"none"}
Function Documentation
hsl_to_rgb()
def tgs.parsers.svg.importer.hsl_to_rgb (h, s, l)
Definition at line 13 of file importer.py.
References tgs.parsers.svg.importer.hue_to_rgb().
Referenced by tgs.parsers.svg.importer.parse_color().
hue_to_rgb()
def tgs.parsers.svg.importer.hue_to_rgb (m1, m2, h)
Definition at line 25 of file importer.py.
Referenced by tgs.parsers.svg.importer.hsl_to_rgb().
parse_color()
def tgs.parsers.svg.importer.parse_color (color, current_color = NVector(0, 0, 0, 1))
Definition at line 153 of file importer.py.
References tgs.parsers.svg.importer.hsl_to_rgb().
parse_svg_etree()
def tgs.parsers.svg.importer.parse_svg_etree (etree, args, kwargs)
Definition at line 857 of file importer.py.
Referenced by tgs.parsers.svg.importer.parse_svg_file().
parse_svg_file()
def tgs.parsers.svg.importer.parse_svg_file (file, args, kwargs)
Definition at line 862 of file importer.py.
References tgs.parsers.svg.importer.parse_svg_etree().
Variable Documentation
nocolor
dictionary tgs.parsers.svg.importer.nocolor = {"none"}
Definition at line 10 of file importer.py.