tgs: tgs.utils.linediff Namespace Reference
tgs.utils.linediff Namespace Reference
Functions
def difflines_str (a, b, widtha=None, widthb=None)
def sideprinter (left, right, widtha=40, widthb=40, prefix="", infix=" | ", suffix="")
def difflines (a, b, widtha=None, widthb=None)
Function Documentation
difflines()
def tgs.utils.linediff.difflines (a, b, widtha = None, widthb = None)
Definition at line 33 of file linediff.py.
References tgs.utils.linediff.difflines_str(), and tgs.exporters.prettyprint().
difflines_str()
def tgs.utils.linediff.difflines_str (a, b, widtha = None, widthb = None)
Definition at line 6 of file linediff.py.
References tgs.utils.linediff.sideprinter().
Referenced by tgs.utils.linediff.difflines().
sideprinter()
def tgs.utils.linediff.sideprinter (left, right, widtha = 40, widthb = 40, prefix = "", infix = " | ", suffix = "")
Definition at line 24 of file linediff.py.
Referenced by tgs.utils.linediff.difflines_str().